---
title: "RWorksheet_Gallo#4c"
author: "Alfe Kevin P. Gallo"
date: "2023-11-22"
output: pdf_document
---
1.
```{r}

library(ggplot2)

head(mpg)
  
summary(mpg)



```

1a.
```{r}
# Show your solutions on how to import a csv file into the environment.

mpgdata <- read.csv("mpg.csv")


```
1b. 
```{r}
# Which variables from mpg dataset are categorical?
str(mpg)

```
1c.
```{r}
# Which are continuous variables?



```
2.
```{r}
#Which manufacturer has the most models in this data set? Which model has the most variations? Show your answe
library(ggplot2)

str(mpg)

model_manu <- table(mpg$manufacturer)
max_manumod <- names(which.max(model_manu))
cat("Manufacturer with the most models:", max_manumod, "\n")

maxmanufacturer_data <- subset(mpg, manufacturer ==  max_manumod)


modelcountsdata <- table(maxmanufacturer_data$model)

maxvarmod <- names(which.max(modelcountsdata))
cat("Model with the most variations:", maxvarmod, "\n")

```
2a.
```{r}
# Group the manufacturers and find the unique models. Show your codes and result.
library(ggplot2)
library(dplyr)


manufacmod <- mpg %>%
  group_by(manufacturer) %>%
  summarize(unique_models = n_distinct(model))


print(manufacmod)



```
2b.
```{r}
# Graph the result by using plot() and ggplot(). Write the codes and its result.

# using plot() 
plot(manufacmod$manufacturer, manufacmod$unique_models, 
     type = "bar", 
     main = "Unique Models per Manufacturer",
     xlab = "Manufacturer",
     ylab = "Number of Unique Models")

#using ggplot() 
library(ggplot2)

ggplot(manufacmod, aes(x = manufacturer, y = unique_models)) +
  geom_bar(stat = "identity", fill = "red") +
  labs(title = "Unique Models per Manufacturer",
       x = "Manufacturer",
       y = "Number of Unique Models") +
  theme_grey()



```
2a
```{r}
#What does ggplot(mpg, aes(model, manufacturer)) + geom_point() show?
ggplot(mpg, aes(model, manufacturer)) + geom_point()

#it shows the points where the manufacturer and models are.

```
2b.
```{r}
#Yes, it is useful

```
3.
```{r}
#. Plot the model and the year using ggplot(). Use only the top 20 observations. Write the codes and its results.

library(ggplot2)

top_20 <- head(mpg, 20)

ggplot(top_20, aes(x = model, y = year)) +
  geom_point() +
  labs(title = "Scatter plot of Model vs Year (Top 20 Observations)",
       x = "Model",
       y = "Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
4.
```{r}

```
