---
title: "RWorksheet_Gallo#4b"
author: "Alfe Kevin P. Gallo"
date: "2023-11-08"
output: pdf_document
---

```{r}
#1 . Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero matrix.
vectorA <- c(1,2,3,4,5)
matrixa <- matrix(vectorA, nrow = 5,ncol = 5)

vectora <-c(0)
matrixA <- matrix(0, nrow =5,ncol =5)

for (i in length(vectorA)) {
  matrixA[i, ] <- abs(vectorA-vectorA[i])
}
print(matrixA)

```
```{r}
#2 Print the string "*" using for() function. The output should be the same as shown in Figur

for(i in 1:5 ){
  newstar <- rep("*",i)
  print(newstar)
}

```
```{r}
#3 Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.

seqnum<- as.numeric(readline("Enter the starting number for the Fibonacci sequence: "))

a <- 0
b <- 1


cat("Fibonacci sequence starting from", seqnum, "up to 500:\n")

repeat {
  if (a >= seqnum) {
    cat(a, " ")
  }
  if (a ==377) {
    break
  }
  tempnum <- a + b
  a <- b
  b <- tempnum
}

cat("\n")




```
```{r}

#4Import the dataset as shown in Figure 1 you have created previously


#4a. What is the R script for importing an excel or a csv file? Display the first 6 rows ofthe dataset? Show your codes and its result

ShoeSdata <- read.csv("Shoe_Sizes")

#4b . Create a subset for gender(female and male). How many observations are there in Male? How about in Female? Write the R scripts and its output.

MaleSub <- subset(ShoeSdata, Gender == "M")
FemaleSub <- subset(ShoeSdata, Gender == "M")

cat("The number of observation in male subset:", nrow(MaleSub),"\n")
cat("The number of observation in female subset:", nrow(FemaleSub),"\n")

#4c  Create a graph for the number of males and females for Household Data. Use plot(),chart type = barplot. Make sure to place title, legends, and colors. Write the R scripts and its result.

GenderRibil <- table(ShoeSdata$Gender)


barplot(GenderRibil, 
        main = "Number of Males and Females in Household Data", 
        xlab = "Gender", 
        ylab = "Count",
        col = c("blue", "pink"), 
        legend.text = c("Male", "Female"))

```
```{r}
#5 a. Create a piechart that will include labels in percentage.Add some colors and title of the chart. Write the R scripts and show its output.

 Dela_Cruz_Fam <- c(60,10,5,25)
  pie(Dela_Cruz_Fam,labels = paste0(Dela_Cruz_Fam,"%"),
      main = "Expenses of Dela Cruz Family",
      col = rainbow(length(Dela_Cruz_Fam)))
  
  legend("topright",legend =c("Food","Electricity","Saving","Miscellaneous"),
         fill = rainbow(length(Dela_Cruz_Fam)))
  
    
```
```{r}
#6 Use the iris dataset

#6a a. Check for the structure of the dataset using the str() function. Describe what youhave seen in the output.

data(iris)
str(iris)

# I saw a data frame of 5 variables which include the numeric measurements for Sepal.Length, Sepal.Width, Petal.Length, and Petal.Width, as well as a factor variable for the Species.
```
```{r}
#6b Create an R object that will contain the mean of the sepal.length, sepal.width,petal.length,and petal.width. What is the R script and its result?



```
